# Generated by Django 5.1.3 on 2024-11-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='purchased_courses',
            field=models.ManyToManyField(blank=True, related_name='purchasers', to='learn.course'),
        ),
    ]
